{% set name = "silx" %}
{% set version = "2.2.1" %}
{% set sha256 = "f5d8b74cd8e1868393e1b4703df68cfe34db556e7e57d6fc57657a641c17663a" %}

package:
  name: silx-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [python_impl == 'pypy']

outputs:
  - name: silx-base
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    build:
      entry_points:
        - silx = silx.__main__:main

    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
      host:
        - python
        - pip
        - wheel
        - setuptools
        - numpy
        - cython >=0.29.31
      run:
        - python
        - packaging
        - h5py
        - fabio >=0.9
        - importlib-resources  # [py==38]

    test:
      imports:
        - silx
        - silx.math # Imports cython extensions
      commands:
        - pip check
      requires:
        - pip

  - name: silx
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('silx-base', max_pin="x.x.x.x") }}
        - pyopencl
        - mako
        - qtconsole
        - matplotlib-base >=3.1.0
        - pyopengl
        - python-dateutil
        - pyqt
        - hdf5plugin
        - scipy
        - pillow
    test:
      commands:
        - silx --help

about:
  home: https://github.com/silx-kit/silx
  license: MIT
  license_family: MIT
  license_file: copyright
  summary: The silx project aims at providing a collection of Python packages to support the development of data assessment, reduction and analysis applications at synchrotron radiation facilities.

  description: |
    The silx project aims at providing a collection of Python packages to
    support the development of data assessment, reduction and analysis
    applications at synchrotron radiation facilities. It aims at providing
    reading/writing different file formats, data reduction routines and a set
    of Qt widgets to browse and visualize data.
  doc_url: http://www.silx.org/doc/silx/latest/
  dev_url: https://github.com/silx-kit/silx

extra:
  recipe-maintainers:
    - CJ-Wright
    - tschoonj
    - vallsv
    - t20100
